### PR TITLE
pointer to About Bitcredit added in intro.ui

### PR DESCRIPTION
**Pull request by thelonecrouton**
cleans up some test stuff that was in previous commit

### CODE REVIEW

**Comment by thelonecrouton** [comment]
added a bunch of simple themes

**Comment by bitcreditscc** [comment]
This is a great first step. I am trying to figure out how we can introduce lite web servers to our client , partly to allow users to "login" to services and also so we can start serving up content like adverts and updated roadmaps. Also allows us to communicate easy when forums are down. 

This is touchy work though

**Comment by gjhiggins** [comment]
I think that risks introducing centralisation - content's gotta come from somewhere. IMO, it'd be more useful to enable [i]others[/i] to set up web servers and offer secure content streams for wallet owners to subscribe to. Nascent trusted oracles, if you like. Also it trims the job down to “just” creating the API and lashing up a Qt web widget for the wallet GUI.

**Comment by bitcreditscc** [comment]
Yes, everyone should be able to serve up content. In fact it could be a revenue stream , with service providers bidding for 2 minute slots for advertising. It should be decentralized and available to all BN users.

**Comment by bitcreditscc** [comment]
As to the original content here, i agree with it. Merging now

**Comment by thelonecrouton** [comment]
It hadn't occurred to me to stick an advert box anywhere, but if it isn't too obnoxious and if the revenue from it goes to backing BCR in some way then why not? Maybe some option to disable it if your BCR balance > x? 

Previous adventures with Google Ads tells me it isn't going to be a huge income, but every little helps, particularly at this stage. The BCT crowd would hate the whole concept, but I don't think they should be who we're aiming at. In fact given the developer hours and all the money that has gone into BTC over the past 6 years, their results in terms of public awareness and adoption are frankly pitiful. Being commercially viable and self-sustaining is not a sin. ;)

And like distribution by bid, objections to ads might diminish when users realise that the revenue is going to directly back their BCR.

**Comment by bitcreditscc** [comment]
Yes, we have to look at sustainability on a global scale. And having Ad removal options based on holdings is a good start. Besides tbh , the types of ads we post will likely be of interest to users. 

As for distribution via bidding, i have a write up that i want you guys to read and it will explain some of the inner workings that i have not made clear yet.

**Pull request merged**
